name: Python application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - BaseTemplate
          - project1
          - project2  # Add new project folders here

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            !~/.cache/pip/log
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          cd ${{ matrix.project }}
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          cd ${{ matrix.project }}
          pytest --maxfail=1 --disable-warnings -q
        continue-on-error: true

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-results-${{ matrix.project }}
          path: ${{ matrix.project }}/test-results/

      - name: Lint code
        run: |
          cd ${{ matrix.project }}
          pip install pylint
          pylint app
          pylint app1  # Adjust or add additional directories if needed
